# Generated by Django 5.2 on 2025-05-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ddq_goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="订单id",
                    ),
                ),
                (
                    "pay_method",
                    models.SmallIntegerField(
                        choices=[
                            (1, "货到付款"),
                            (2, "微信支付"),
                            (3, "支付宝"),
                            (4, "银联支付"),
                        ],
                        default=3,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(default=1, verbose_name="商品数量"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="商品总价"
                    ),
                ),
                (
                    "transit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单运费"
                    ),
                ),
                (
                    "order_status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "待支付"),
                            (2, "待发货"),
                            (3, "待收货"),
                            (4, "待评价"),
                            (5, "已完成"),
                        ],
                        default=1,
                        verbose_name="订单状态",
                    ),
                ),
                ("trade_no", models.CharField(max_length=128, verbose_name="支付编号")),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "ddq_order_info",
            },
        ),
        migrations.CreateModel(
            name="OrderGoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                ("count", models.IntegerField(default=1, verbose_name="商品数目")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="商品价格"
                    ),
                ),
                ("comment", models.CharField(max_length=256, verbose_name="评论")),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddq_goods.goodssku",
                        verbose_name="商品SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单商品",
                "verbose_name_plural": "订单商品",
                "db_table": "ddq_order_goods",
            },
        ),
    ]
