# Generated by Django 5.2 on 2025-05-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddq_order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergoods",
            name="comment",
            field=models.CharField(default="", max_length=256, verbose_name="评论"),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="trade_no",
            field=models.CharField(default="", max_length=128, verbose_name="支付编号"),
        ),
    ]
