# Generated by Django 5.2 on 2025-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddq_user", "0002_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="zip_code",
        ),
        migrations.AlterField(
            model_name="balance",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=10000.0, max_digits=10, verbose_name="余额"
            ),
        ),
    ]
