# Generated by Django 5.2 on 2025-05-03 09:06

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="商品SPU名称")),
                (
                    "detail",
                    tinymce.models.HTMLField(blank=True, verbose_name="商品详情"),
                ),
            ],
            options={
                "verbose_name": "商品SPU",
                "verbose_name_plural": "商品SPU",
                "db_table": "ddq_goods",
            },
        ),
        migrations.CreateModel(
            name="GoodsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="种类名称")),
                ("logo", models.CharField(max_length=20, verbose_name="标识")),
                (
                    "image",
                    models.ImageField(upload_to="type", verbose_name="商品类型图片"),
                ),
            ],
            options={
                "verbose_name": "商品种类",
                "verbose_name_plural": "商品种类",
                "db_table": "ddq_goods_type",
            },
        ),
        migrations.CreateModel(
            name="IndexPromotionBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="活动名称")),
                ("url", models.URLField(verbose_name="活动链接")),
                (
                    "image",
                    models.ImageField(upload_to="banner", verbose_name="活动图片"),
                ),
                ("index", models.SmallIntegerField(default=0, verbose_name="展示顺序")),
            ],
            options={
                "verbose_name": "主页促销活动",
                "verbose_name_plural": "主页促销活动",
                "db_table": "ddq_index_promotion",
            },
        ),
        migrations.CreateModel(
            name="GoodsSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="商品名称")),
                ("desc", models.CharField(max_length=256, verbose_name="商品简介")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="商品价格"
                    ),
                ),
                ("unite", models.CharField(max_length=20, verbose_name="商品单位")),
                (
                    "image",
                    models.ImageField(upload_to="goods", verbose_name="商品图片"),
                ),
                ("stock", models.IntegerField(default=1, verbose_name="商品库存")),
                ("sales", models.IntegerField(default=0, verbose_name="商品销量")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "下线"), (1, "上线")],
                        default=1,
                        verbose_name="商品状态",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddq_goods.goods",
                        verbose_name="商品SPU",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddq_goods.goodstype",
                        verbose_name="商品种类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "ddq_goods_sku",
            },
        ),
        migrations.CreateModel(
            name="GoodsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="goods", verbose_name="图片路径"),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddq_goods.goodssku",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
                "db_table": "ddq_goods_image",
            },
        ),
        migrations.CreateModel(
            name="IndexGoodsBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                ("image", models.ImageField(upload_to="banner", verbose_name="图片")),
                ("index", models.SmallIntegerField(default=0, verbose_name="展示顺序")),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddq_goods.goodssku",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "首页轮播商品",
                "verbose_name_plural": "首页轮播商品",
                "db_table": "ddq_index_banner",
            },
        ),
        migrations.CreateModel(
            name="IndexTypeGoodsBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="对象首次创建的时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="对象最后一次修改的时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="设置为True时表示逻辑删除，不实际从数据库中删除",
                        verbose_name="删除标记",
                    ),
                ),
                (
                    "display_type",
                    models.SmallIntegerField(
                        choices=[(0, "标题"), (1, "图片")],
                        default=1,
                        verbose_name="展示类型",
                    ),
                ),
                ("index", models.SmallIntegerField(default=0, verbose_name="展示顺序")),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddq_goods.goodssku",
                        verbose_name="商品SKU",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddq_goods.goodstype",
                        verbose_name="商品类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "主页分类展示商品",
                "verbose_name_plural": "主页分类展示商品",
                "db_table": "ddq_index_type_goods",
            },
        ),
    ]
