# Generated by Django 5.2 on 2025-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddq_goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpromotionbanner",
            name="url",
            field=models.CharField(max_length=256, verbose_name="活动链接"),
        ),
    ]
