# Generated by Django 5.2 on 2025-05-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddq_goods", "0002_alter_indexpromotionbanner_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IndexPromotionBanner",
        ),
        migrations.DeleteModel(
            name="IndexTypeGoodsBanner",
        ),
    ]
